SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID FROM EMPLOYEES;


-- LEts say we want to find the employees fill name with their manager's

SELECT *
FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2
                             ON E1.EMPLOYEE_ID = E2.MANAGER_ID;


SELECT E2.EMPLOYEE_ID, E2.FIRST_NAME, E2.LAST_NAME, E1.FIRST_NAME as MANAGER_NAME, E1.MANAGER_ID, E2.MANAGER_ID
FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2
                             ON E1.EMPLOYEE_ID = E2.MANAGER_ID;